language: go
go:
  - 1.6

sudo: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: s3
    access_key_id: "UIe/rs7aIklo26qjh36JosI5Ft0DaBRIY/CCxQFCdZmd44dN9dyU3LbN0hkIpIKpoEwSrFQ/YLkxP1xkjzq1RzSSJJI15D9OICDsQQfEoEnBTT0pv48zNJW3QCMoLu2x6sD76adcHCjBs6u9lM8XbXd3LKvEWvfvmiYbwc6UvIIRn0Bil76rzexfzCHMk7cat2xV5+KYPjpHlfBuGCGC6doOhfsQ26kdprR2RoOceiG7fcdluyyoWdWv33G63D/yL3TL2dprciQqTkDxSSr+rWFu2+ZOD2afD5Km6sScX66eN51MoDsUrKKCEfNafNNcnIrK7iZzbR+YFyc6p9O06VR0oUlRVcVSVcENHl/DRQ/AywvzZXEanPv2EzgzSqRnkYHdXyk8z98QkpBIIUq6nbauEh7Kl/jZhc103o9F5OPB1dRcTx70xZmvBqVuU7p7OJTuCjCxyD+h2+00NUjUH1t5xhlfK+9geSoMmZ7Fo1dOrtVv6eGW9XV6HJWJ66tA1tDlgYf2Ej47CxPrfiXbj/0mud7G+d4W2WExrAuF+57juqax1PrsslZU+0LeyrSCgOdCtHNeQKgvJzHM9tR9IBX2HV/sIqGhuObN/5UfHuMTSmavnafVH4Rgf8uadS6apCHjOvkwS0/dq3T8hVM8W21rpej99jkzouFLGL86nZk="
    secret_access_key: "s8mTgec+rp7Ra0gN4TpOKQ+1GauVX2VrywgHgGbBvJGgNSk/a0l9VikyNzXs3hf8hLnL3YARs+twE7uuSuZuJwwHRr1qRy/brCs/VshFAUgjvcStanOVtyiECmwRogSOIOOwkPZWJngo7vgOHnlyCAX6maREQY1GV2CGcn6A6APv/c3vR1iJp/AXzQaiyu3LZw/f332iqCMPnc5pVWkyj/ykSp+qbZMqjZKy1dgdAJdqr6zAwUS4Hr7l5i6p9dLLa/NNSQ2YVL7HYdw5p7HpSYUacGrrLqmcVfDR/neBzX2iKSa70kwc8k1iVDZhjNa9+vEHEOmcH1p7NiJi/DqFDjEpCX2Ktgfuv5B2uo6lvQ8PmoRNFeFLLEZ1j3H8h/JuwMmhQq6yYeCg8r+v7GQTJdSPlasQcMTbUD9fLQkwPADk8C6ipRB9HnS0Dy1CrmFSLieuAQgAusAZcyx/f0b0r5zaso6XqJtUM2GXJXy0fVV6CMxp8mYHA3VhQWew29z4L9egr4qMIMrv6gWU68TiaMAFJn1nstJGlW4Cv+PZSNvCmrXVNHds3oRXqxHbFaxwdwuAk9WdDwRwdmwq9P7jgTSZmrkhiEjub1hzmSwXOB8yts2JMrwCVEgkUCmnM1aVzQxZId54h12P+UfKlhxZ0yq72++IJDn9VFxbYRZoy/s="
    bucket: "ImHoNDvr8IQzOY0KjxlxSWd4Xugkv4iI5v+Lifd2yaAPqTSAYaM83oW9/SppnwrxVoEj1MwbvHLUw9o7+BAqhMSYDainprwaXP07RC/go/JoSQJ/tQq8/mgs3/pLwUIGnxfm03NrjCxC4YtNzxvrWsblQyfydg8yQPMlB6ZJISUJLcMHoSlExBqCpo+4uZxgX3Bf6JJaqIC9JwnG/U2Tu3haPY8jKfgqtOVCCvX7AixMf3ih/mqyPKlH9fgXjgfySxl5X/6BdGnEIAUrEGCG+TDXQQiocVTqaFKio9nQbqbkrpyl4G0beJfKxbcjY8RVg8ZhTgpE5/c3CsTnJze940wrwgWu373ktJ1/dQYIf10QGii+aTeEIIEudu4L3CrimTPCeKrV+YDN+cX8W8AkdqlgSZkcE2ncKwlZGBRT0iCSbtFKPDaiaH9ZYDQX4iyF/x67f9VHlyVzFfzfBAX9Fz36R2QqEc+w+z3K33BK4XcZtgm6udyYIIFVWgkpwKuEI+090HPPsldvK89JKorMRBHMoSzgnLrUsRj7y3c+kirdaOX/kHe5LFxVqKPcLp0r3rYT9TuxKskawuY/YtIuB9VXdIV8KiDp0+fE4W8Ou6x/mjPL/VA3fjgodQ9l4qH8Y7LmNyBnIoKB3M13+wTVBRnbIh/FWC/S/Dbra25R0Ww="
    region: us-east-1
    local_dir: public
    skip_cleanup: true
