language: go
go:
  - 1.6

sudo: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: s3
    access_key_id:
      secure: "kdiZH7yFaZTYTzTZiSUN6D8GzrhIvHzRR62wBK9qxADQI2UZe0TIHpKxpsGMXEK/41EWOTpzkhp75o6By+Or7OAZ0BOxCjngtjxU28fUTyLEbs1hnGl025HzrXIw/oQ83AWbw8xGZcJ8k/scY2M/5yN47t1vdPMU1HnS5iU/UDB+zqm9tPnxg0GQDeM2RA6qLI8bUo8dk3TKnfe60BAQpbBwwoLDYjPmAX0+GB8OghkMRA+sjLB/idEzhE3kgLcoKFxTjZVVMztU031EL1QmPG6lwzDNqCKVrqkkTWT5CjLlwNLcbnKqcX0Ijk2vZaSEFxLjvi9+8KUz6F8lsTKATg3e6Yibb5aEidDnZJ79p0SjXUlV/GktTRWYBidPf4cUckZGQ8KM7X9s5bHR30gLRcpJDevIMICyciptNL2jaRl4F5EwgF7BN2lq0RMkte8Xz65BP6n6BLD3H5y1aI1yPNcp1iYWPohTw/c7BSpbAbQrvcFTpNXl8VrZNwkRgUDAIc4va79QWkO8yNnot2m0WsU83YLwuytUP9fdgNm9/OjunfGMUTs36WwaVKmYuRsZ3SdsOfutvd5XQ/c/AGVzSz261q7bYuFHdqiwrrG3sX91gD5GrZY1G/2lzZyjx/3fG9JOXMRlUo2fKmoRKteAzuhTRftoIZTNtFdMKbz58zc="
    secret_access_key:
      secure: "0Ee0sJLwmB/C9rFhyWjEzbIkzUjhQutydN3FwfW9VFBvJO97TCKhBL2PyEqyqq9RrCEBVEXLfGbhd9TBmN05Q8CP6iGN5kXap5zsDjf4OUX92ysM4LPIWzh4eSfrWGC8TvgVlyVkfGzvloW4o5YavZmCzyQfUcX+48TwHkTAWxkYGV+cmoQv7DTiwOE7Bg5yXY4757813YZ4eiYRPaifN74Vs/PoYxrlphNw/ksolcKuLWzOoqclnHMcRO8JFSpTOXFKYr6Nt7JaiazUplwsm/VXG2iwcWFDd9SE1r+uO4x7CiqeHbYEld7a/lMhgAMxkBGQHq2WKT+D1OfrWnlv4F9SXIyUy53+8VH7/Yz6xLWlH6nNPeFD7rzdBfKJ6wLNv/odg4bw38ATjb5Z1zlyA2dTJF1+tmpdcgjQPWXBEDEmpFBCmoWqItITyab4Mc606KkKZ6auSxdPDKOxyciOTNODvJ5jjz8L+17lgbPsgM1SU19ardIWkrG/KuWoZ0PH69mkxql++Bn5Ysiy/MF+pmZTyOHXjoT7Nuc6RLgBacHhoNR7NwhquB+hRhFV1YPVo66psTEGcZhT04XBbStALgxfgeXvrjigGMWOoMLFq6bPKwS3LJMMXuN7yBztmMopmXiMZtFm3FqOGd3nLPcevjsYUqZmvvuhKQZN6ZunBl0="
    bucket:
      secure: "YwIvU4ftjos3Zb+cQq0WpA2sigkaAaD/7vFLZV0AeElyYZfjW2ea40TInIk2/H7lhOlIQGsMmZkTb4ROCCGWihFVuYb/CPkIoFgKkEItla9t0MHqNzpfpIYYr8KwpknhSdIlcGwaeg3IvPCcJJJJtmHWy4XlBWiSVhpXQpeW3oeVMmmHsSNBklU40HMgnytlJsSDpFzKBazuJ1rg7AK9MvVKONCMgznxVGS8x6zfw51SIE2JpmVbxMec76FCw1Pn5TRFNHHxvYuYjzv9GaOielu0+x+rljg/+NhwEpVb+q6JrKKtl9yulUykvEDjb1kPSydVNrMGu13318Uq3fxMnIAYpcM5vXrQ9IUQg3LAOJUugMVEB4F5U8i7EVMfDI4okfo6R4qDJyxjizcmm6zfGyRk8hG9ucaPozsYyVFPmLhE78SqutJ9y3wTb1cKcyDDwYvasBLEiXaMS/J4Y/Au7r4/t9/r1P2yECrIY+bvX4CPW1UatyDJXF9HnxyMFkyEeypQi8OGUkz1YUCtgSpVW7Wo1hj44bveLNSSU9+ogI0Gqda+rufN48Hkuq65yjrCNbsN8y5z5nQNJHQFt8Vc4PMEN/w6fQsAIZKzXhZbh2kkKEBb9Ip+kmsc18QPai403pTStH/Rhs6YUsXVO5a7M13vkkaKvkUstzTfEBjH/E4="
    region: us-east-1
    local_dir: public
    skip_cleanup: true
