language: go
go:
  - 1.6

sudo: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: s3
    access_key_id:
      secure: "kdiZH7yFaZTYTzTZiSUN6D8GzrhIvHzRR62wBK9qxADQI2UZe0TIHpKxpsGMXEK/41EWOTpzkhp75o6By+Or7OAZ0BOxCjngtjxU28fUTyLEbs1hnGl025HzrXIw/oQ83AWbw8xGZcJ8k/scY2M/5yN47t1vdPMU1HnS5iU/UDB+zqm9tPnxg0GQDeM2RA6qLI8bUo8dk3TKnfe60BAQpbBwwoLDYjPmAX0+GB8OghkMRA+sjLB/idEzhE3kgLcoKFxTjZVVMztU031EL1QmPG6lwzDNqCKVrqkkTWT5CjLlwNLcbnKqcX0Ijk2vZaSEFxLjvi9+8KUz6F8lsTKATg3e6Yibb5aEidDnZJ79p0SjXUlV/GktTRWYBidPf4cUckZGQ8KM7X9s5bHR30gLRcpJDevIMICyciptNL2jaRl4F5EwgF7BN2lq0RMkte8Xz65BP6n6BLD3H5y1aI1yPNcp1iYWPohTw/c7BSpbAbQrvcFTpNXl8VrZNwkRgUDAIc4va79QWkO8yNnot2m0WsU83YLwuytUP9fdgNm9/OjunfGMUTs36WwaVKmYuRsZ3SdsOfutvd5XQ/c/AGVzSz261q7bYuFHdqiwrrG3sX91gD5GrZY1G/2lzZyjx/3fG9JOXMRlUo2fKmoRKteAzuhTRftoIZTNtFdMKbz58zc="
    secret_access_key:
      secure: "0Ee0sJLwmB/C9rFhyWjEzbIkzUjhQutydN3FwfW9VFBvJO97TCKhBL2PyEqyqq9RrCEBVEXLfGbhd9TBmN05Q8CP6iGN5kXap5zsDjf4OUX92ysM4LPIWzh4eSfrWGC8TvgVlyVkfGzvloW4o5YavZmCzyQfUcX+48TwHkTAWxkYGV+cmoQv7DTiwOE7Bg5yXY4757813YZ4eiYRPaifN74Vs/PoYxrlphNw/ksolcKuLWzOoqclnHMcRO8JFSpTOXFKYr6Nt7JaiazUplwsm/VXG2iwcWFDd9SE1r+uO4x7CiqeHbYEld7a/lMhgAMxkBGQHq2WKT+D1OfrWnlv4F9SXIyUy53+8VH7/Yz6xLWlH6nNPeFD7rzdBfKJ6wLNv/odg4bw38ATjb5Z1zlyA2dTJF1+tmpdcgjQPWXBEDEmpFBCmoWqItITyab4Mc606KkKZ6auSxdPDKOxyciOTNODvJ5jjz8L+17lgbPsgM1SU19ardIWkrG/KuWoZ0PH69mkxql++Bn5Ysiy/MF+pmZTyOHXjoT7Nuc6RLgBacHhoNR7NwhquB+hRhFV1YPVo66psTEGcZhT04XBbStALgxfgeXvrjigGMWOoMLFq6bPKwS3LJMMXuN7yBztmMopmXiMZtFm3FqOGd3nLPcevjsYUqZmvvuhKQZN6ZunBl0="
    bucket:
      secure: "1oH+8gvRT4heVZEuIQlkgIVOI5r1c81xnjBGIemy4AAmX3yBERdR44dZ18lyruJv8jyKXoisPckwcJVD+/Fimcq8PtJwG1LDTBXErCT2iI6Vuj0GQ/jDctyWlq96VHHrXVYj9NawcUwnxG/owVAXMLo1FKbak/JOXCqNGb8FKIKYQTxfHr6MmQYjVsH1c0k3MpnyQp/pJuJ9zb/SIQ1wa/owGEKPQD6QYz/LvJ3EwRr8GP7hJHX5wv2jlS88576ZujaOvCj0a5aFhr9qtrD7GM63Ury2cRhvzYbsMZ0uBeIYNbsBypEmN53tw24wXYxji70tpOlbMCRQJIaIVxq7clV60FHriyTKLrobo8W4IxWegHbY+fbWWTuV5ji1OTDofwepAa/VEvSvUR/wNUndQt0IQGr70eQ/QAg2j7JnnzzaLVzCXg07GrtaR2h6owH+lac4la1QDLnl+dvD3X8cKLpRzi8bQg8bWlyqaE5iiM6QyBdVSvEzQL+44Jb5sCd/crMJB3oeRAjlUmNY0d/gS5pAE9d4pXfoEQ0HDjmgGJLVcGEZevHlxIzrRQl0YnPu8X/av1zApV2PPdYWytFjbyOb4xxB8bMNakp1d9i529DGPR7EyGTa3S75F7fzz/uEk+LHCocRJxmcgvcm1J3EBy7iEbhm3fTY/+0zAi/2sbM="
    region: us-east-1
    local_dir: public
    skip_cleanup: true
